version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: gravitypm-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-waf.conf:/etc/nginx/nginx-waf.conf
      - ./ssl:/app/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - gravitypm

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gravitypm-backend
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    networks:
      - gravitypm

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gravitypm-frontend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - ENVIRONMENT=production
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - gravitypm

  redis:
    image: redis:alpine
    container_name: gravitypm-redis
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gravitypm

  redis-node-1:
    image: redis:alpine
    container_name: gravitypm-redis-node-1
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_node1_data:/data
    networks:
      - gravitypm

  redis-node-2:
    image: redis:alpine
    container_name: gravitypm-redis-node-2
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6381
    ports:
      - "6381:6381"
    volumes:
      - redis_node2_data:/data
    networks:
      - gravitypm

  # Monitoring stack
  prometheus:
    image: prom/prometheus:latest
    container_name: gravitypm-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - gravitypm

  grafana:
    image: grafana/grafana:latest
    container_name: gravitypm-grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - gravitypm

  node-exporter:
    image: prom/node-exporter:latest
    container_name: gravitypm-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - gravitypm

  # ELK stack for logging
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: gravitypm-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - gravitypm

  logstash:
    image: docker.elastic.co/logstash/logstash:8.5.0
    container_name: gravitypm-logstash
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - ./monitoring/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./monitoring/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - elasticsearch
    networks:
      - gravitypm

  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.0
    container_name: gravitypm-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - gravitypm

  # Database monitoring (for local MongoDB - comment out if using MongoDB Atlas)
  mongodb-exporter:
    image: percona/mongodb_exporter:latest
    container_name: gravitypm-mongodb-exporter
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://mongodb-primary:27017
    depends_on:
      - mongodb-primary
    networks:
      - gravitypm

  # MongoDB Replica Set for High Availability
  mongodb-primary:
    image: mongo:6.0
    container_name: gravitypm-mongodb-primary
    command: --replSet rs0 --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: gravitypm
    ports:
      - "27017:27017"
    volumes:
      - mongodb_primary_data:/data/db
      - ./scripts/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    networks:
      - gravitypm

  mongodb-secondary:
    image: mongo:6.0
    container_name: gravitypm-mongodb-secondary
    command: --replSet rs0 --bind_ip_all
    depends_on:
      - mongodb-primary
    ports:
      - "27018:27017"
    volumes:
      - mongodb_secondary_data:/data/db
    networks:
      - gravitypm

  mongodb-arbiter:
    image: mongo:6.0
    container_name: gravitypm-mongodb-arbiter
    command: --replSet rs0 --bind_ip_all
    depends_on:
      - mongodb-primary
    ports:
      - "27019:27017"
    volumes:
      - mongodb_arbiter_data:/data/db
    networks:
      - gravitypm

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: gravitypm-redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    depends_on:
      - redis
    networks:
      - gravitypm

volumes:
  redis_data:
  redis_node1_data:
  redis_node2_data:
  prometheus_data:
  grafana_data:
  elasticsearch_data:
  mongodb_primary_data:
  mongodb_secondary_data:
  mongodb_arbiter_data:

networks:
  gravitypm:
    driver: bridge
